// 
// Do not edit this file, it is automatically generated!
// To generate this file, "make design.h" in the rtl directory.
// 
#ifndef DESIGN_H
#define DESIGN_H

#define	WBUBUS_MASTER
#define	DDR3SCOPE1_SCOPC
#define	DDR3SCOPE2_SCOPC
#define	DDR3_CONTROLLER_ACCESS
#define	BKRAM_ACCESS
#define	SIREFCLK_ACCESS
#define	I2CDMA_ACCESS
#define	DDR3_PHY_ACCESS
#define	FAN_ACCESS
#define	I2CCPU_ACCESS
#define	BUSCONSOLE_ACCESS
#define	INCLUDE_ZIPCPU
#define	VERSION_ACCESS
#define	I2CSCOPE_SCOPC
#define	CFG_ACCESS
#define	DDR3SCOPE3_SCOPC
#define	GPIO_ACCESS
#define	SPIO_ACCESS
#define INCLUDE_DMA_CONTROLLER
#define INCLUDE_ACCOUNTING_COUNTERS
#ifdef	VERILATOR
#endif
#ifdef	BKROM_ACCESS
#else
#ifdef	FLASH_ACCESS
#else
#endif	// FLASH_ACCESS
#endif	// BKROM_ACCESS
#ifdef	BKROM_ACCESS
#else
#endif
#ifdef	VERILATOR
#endif
#ifndef	VERILATOR
#endif
#ifdef	DDR3SCOPE1_SCOPC
#else	// DDR3SCOPE1_SCOPC
#endif	// DDR3SCOPE1_SCOPC
#ifdef	DDR3SCOPE2_SCOPC
#else	// DDR3SCOPE2_SCOPC
#endif	// DDR3SCOPE2_SCOPC
#ifdef	DDR3_CONTROLLER_ACCESS
#else	// DDR3_CONTROLLER_ACCESS
#endif	// DDR3_CONTROLLER_ACCESS
#ifdef	BKRAM_ACCESS
#else	// BKRAM_ACCESS
#endif	// BKRAM_ACCESS
#ifdef	SIREFCLK_ACCESS
#else	// SIREFCLK_ACCESS
#endif	// SIREFCLK_ACCESS
#ifdef	I2CDMA_ACCESS
#else	// I2CDMA_ACCESS
#endif	// I2CDMA_ACCESS
#ifdef	FAN_ACCESS
#else	// FAN_ACCESS
#endif	// FAN_ACCESS
#ifdef	I2CCPU_ACCESS
#ifdef	EDID_ACCESS
#else
#endif
#ifdef	I2CDMA_ACCESS
#else
#endif
#else	// I2CCPU_ACCESS
#endif	// I2CCPU_ACCESS
#ifdef	BUSCONSOLE_ACCESS
#ifdef	SMI_CONSOLE
#else
#endif
#else	// BUSCONSOLE_ACCESS
#endif	// BUSCONSOLE_ACCESS
#ifdef	INCLUDE_ZIPCPU
#ifdef INCLUDE_DMA_CONTROLLER
#else
#endif
#ifdef INCLUDE_ACCOUNTING_COUNTERS
#else
#endif
#ifdef	VERILATOR
#else
#endif
#ifdef	ZIPSCOPE_SCOPE
#else
#endif
#else	// INCLUDE_ZIPCPU
#endif	// INCLUDE_ZIPCPU
#ifdef	VERSION_ACCESS
#else	// VERSION_ACCESS
#endif	// VERSION_ACCESS
#ifdef	I2CSCOPE_SCOPC
#else	// I2CSCOPE_SCOPC
#endif	// I2CSCOPE_SCOPC
#ifdef	WBUBUS_MASTER
#ifndef	BUSPIC_ACCESS
#ifdef	INCLUDE_ZIPCPU
#else
#endif
#endif
#ifdef	SMI_CONSOLE
#else
#endif
#ifdef	SMI_CONSOLE
#endif
#else	// WBUBUS_MASTER
#endif	// WBUBUS_MASTER
#ifdef	CFG_ACCESS
#ifdef	VERILATOR
#else
#endif
#else	// CFG_ACCESS
#endif	// CFG_ACCESS
#ifdef	DDR3SCOPE3_SCOPC
#else	// DDR3SCOPE3_SCOPC
#endif	// DDR3SCOPE3_SCOPC
#ifdef	GPIO_ACCESS
#else	// GPIO_ACCESS
#endif	// GPIO_ACCESS
#ifdef	SPIO_ACCESS
#else	// SPIO_ACCESS
#endif	// SPIO_ACCESS

#ifndef	DATESTAMP
#define DATESTAMP 0x20230906
#define BUILDTIME 0x00175104
#endif

#endif // DESIGN_H
